apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-cicd-kubernetes-ipssi
  namespace: dev
  labels:
    app: myapp-cicd-kubernetes-ipssi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-cicd-kubernetes-ipssi
  template:
    metadata:
      labels:
        app: myapp-cicd-kubernetes-ipssi
    spec:
      containers:
        - name: myapp-cicd-kubernetes-ipssi
          image: nsabeteisfahaniipssi/myapp-cicd-kubernetes-ipssi:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
