apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-cicd-kubernetes-ipssi
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: myapp-cicd-kubernetes-ipssi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp-cicd-kubernetes-ipssi
                port:
                  number: 80
